### ISSUE TITLE
The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by atirtahirgroupdocs** [groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC#67]
This issue is raised in https://forum.groupdocs.com/t/consistently-facing-issue-the-process-cannot-access-the-file-because-it-is-being-used-by-another-process-in-asp-net-mvc/9574.
Hi,
When a file is uploaded, edited and save button is pressed, application gives an exception. Please have a look at the following screenshots.
![image](https://user-images.githubusercontent.com/15940608/114656037-d42cc300-9d06-11eb-81be-e9ad40f154d8.png)

![image (1)](https://user-images.githubusercontent.com/15940608/114656021-cf680f00-9d06-11eb-924e-152f015fd53a.png)

Below is the sample code:

```
[HttpPost]
        [Route("annotate")]
        public HttpResponseMessage AnnotateAsync(AnnotationPostedDataEntity annotateDocumentRequest)
        {
            AnnotatedDocumentEntity annotatedDocument = new AnnotatedDocumentEntity();
            try
            {
                // get/set parameters
                string documentGuid = annotateDocumentRequest.guid;
                string password = annotateDocumentRequest.password;
                string documentType = SupportedImageFormats.Contains(Path.GetExtension(annotateDocumentRequest.guid)) ? "image" : annotateDocumentRequest.documentType;
                string tempPath = GetTempPath(documentGuid);

                AnnotationDataEntity[] annotationsData = annotateDocumentRequest.annotationsData;
                // initiate list of annotations to add
                List<AnnotationBase> annotations = new List<AnnotationBase>();

                using (GroupDocs.Annotation.Annotator annotator = new GroupDocs.Annotation.Annotator(documentGuid, GetLoadOptions(password)))
                {
                    IDocumentInfo info = annotator.Document.GetDocumentInfo();

                    for (int i = 0; i < annotationsData.Length; i++)
                    {
                        AnnotationDataEntity annotationData = annotationsData[i];
                        PageInfo pageInfo = info.PagesInfo[annotationsData[i].pageNumber - 1];
                        // add annotation, if current annotation type isn't supported by the current document type it will be ignored
                        try
                        {
                            BaseAnnotator baseAnnotator = AnnotatorFactory.createAnnotator(annotationData, pageInfo);
                            if (baseAnnotator.IsSupported(documentType))
                            {
                                annotations.Add(baseAnnotator.GetAnnotationBase(documentType));
                            }
                        }
                        catch (Exception ex)
                        {
                            throw new GroupDocs.Annotation.Exceptions.AnnotatorException(ex.Message, ex);
                        }
                    }
                }

                // Add annotation to the document
                RemoveAnnotations(documentGuid, password);
                // check if annotations array contains at least one annotation to add
                if (annotations.Count != 0)
                {
                    using (GroupDocs.Annotation.Annotator annotator = new GroupDocs.Annotation.Annotator(documentGuid, GetLoadOptions(password)))
                    {
                        foreach (var annotation in annotations)
                        {
                            annotator.Add(annotation);
                        }
                        annotator.Save(tempPath);
                    }

                    if (File.Exists(documentGuid))
                    {
                        File.Delete(documentGuid);
                    }

                    File.Move(tempPath, documentGuid);

                }

                annotatedDocument = new AnnotatedDocumentEntity();
                annotatedDocument.guid = documentGuid;
                annotatedDocument.fileByte = File.ReadAllBytes(documentGuid);
                if (annotateDocumentRequest.print)
                {
                    annotatedDocument.pages = GetAnnotatedPagesForPrint(password, documentGuid);
                    File.Move(documentGuid, annotateDocumentRequest.guid);
                }
            }
            catch (Exception ex)
            {
                // set exception message
                return Request.CreateResponse(HttpStatusCode.InternalServerError, new Ultrabot.Web.UI.Annotation.Common.Resources.Resources().GenerateException(ex));
            }

            return Request.CreateResponse(HttpStatusCode.OK, annotatedDocument);
        }
```

**Comment by kegor** [comment]
Hi @atirtahirgroupdocs, we can't reproduce such issue using our `.jpg` file on sample app version from the `master` branch.
So could you please add information about annotation type that was adding by the user and attach `.jpg`-file on which issue was met.

**Comment by BossRizwan** [comment]
@kegor 
but I am facing an issue Kindly Check the video:

=> https://youtu.be/UnEKwhrDM1w

**Comment by kegor** [comment]
Hi @ImSMRizwan,
I tried to reproduce the problem using, I guess, one of yours images, and mentioned in video annotations types, but still I didn't met the issue (please take a look at the [gif](https://user-images.githubusercontent.com/17431807/114887687-599c9a00-9e11-11eb-9199-ddcbaa9b0bd3.gif)-animation).

I would like to mention that my manual test was made on `master`-branch of the current sample app (https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC).

I'll suggest you to try reproduce same steps on sample app build from re-cloned repository or from master-branch code downloaded as zip-archive.

**Comment by ImSMRizwan** [comment]
Thanks for your comment. 
It's working fine. Now, I find another bug, kindly check the gif animation ![gif-notsaved](https://user-images.githubusercontent.com/17806022/114894684-4812bc80-9e28-11eb-9668-e85254b78e31.gif)

After save I download the image file but it's not showing my editing on the downloaded image. kindly check it also. I am waiting for your response. it would be best for me if you reply soon.

best regards

**Comment by kegor** [comment]
Hi @ImSMRizwan.

Thank you for your request. We work on your issue and when it will be fixed we will notify you here.

**Comment by kegor** [comment]
Hi @ImSMRizwan,

The issue has been resolved. Please checkout latest commit from master branch GroupDocs.Annotation-for-.NET-MVC.

Best Regard
Egor.

**Comment by ImSMRizwan** [comment]
Dear @kegor, I found 2 more issues, kindly check the video => https://youtu.be/UJZS_Cd1_AQ

first, some of the annotation options are not saved (.pdf), and the second is a 14-pages pdf file are not loaded, kindly check it also,

best regards Muhammad rizwan

**Comment by kmehmoodkhan** [comment]
Dear support, any timeline on these issues. We are interested in purchasing this tool, can you please let us know the timelines?

**Comment by kmehmoodkhan** [comment]
Any tentative timeline? because we have to make a decision on the tool selection, your reply will help us finalize our decision. Thanks

**Comment by bobkovalex** [comment]
Hi @kmehmoodkhan 

In order for us to provide any ETA we need to investigate the issue. We're already working on it.
So we will get back to you ASAP.

Thanks.

Regards,
Alex

**Comment by kegor** [comment]
Hi @ImSMRizwan,

I tried to reproduce the problem using our multi-page PDF-file and all available now annotations types and I downloaded resulted file with all annotations applied (please take a look at these gif-animations: 
[adding](https://user-images.githubusercontent.com/17431807/115343808-1f3a5080-a1b5-11eb-8b2f-ba99c446c814.gif) and [viewing](https://user-images.githubusercontent.com/17431807/115343854-2bbea900-a1b5-11eb-90da-d49bf232e48f.gif)).

If you still facing with the issue could you please share your PDF-file and reproducing steps.

Thank you,
Egor.

**Comment by kmehmoodkhan** [comment]
Hi @kegor, thanks for the reply. Everything works, in the same way, the way you have shown in the video but after completing these steps when we save the annotated pdf, some of the annotations are lost as @ImSMRizwan mentioned. Can you please try to save the document on a local drive or any other storage like google drive etc and then see whether all the annotations are still there or disappear? thanks

**Comment by ImSMRizwan** [comment]
Dear @kegor, I am still facing issues. 

Kindly find the attachment files.
[6th,sci,MS.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/files/6342946/6th.sci.MS.pdf)
[Muhammad-Rizwan.pdf](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/files/6342948/Muhammad-Rizwan.pdf)

Issue #1: https://drive.google.com/file/d/1c5TxrIH7cTr6Yu-AoiDjLzmNSOzQebyq/view?usp=sharing
Issue #2: https://drive.google.com/file/d/1htrdtqCSJfcpoEBmmIBMH9JNKTIYtFiy/view?usp=sharing

**Comment by bobkovalex** [comment]
Hi @kmehmoodkhan @ImSMRizwan 

We've released an improvement which should fix document not opening issue, please checkout latest commit fro master branch.

As for not all annotations are saved/exported we are working on the fix and will release it soon (ASAP).

Thanks.

Regards,
Alex

**Comment by bobkovalex** [comment]
@kmehmoodkhan @ImSMRizwan

We've released another improvement which should fix an issue with missing annotations.
Please note that Google Drive preview might now support all annotation types, instead open document locally using Adobe or other similar application.

Make sure to:
1. Checkout latest commit from master branch;
2. Apply license before running GroupDocs.Annotation-for-.NET-MVC;
In case if you do not have license yet, you can request a temporary licence from [here](https://purchase.groupdocs.com/temporary-license).

Regards,
Alex

**Comment by ImSMRizwan** [comment]
@bobkovalex 

I have checked, But still facing missing some annotations options. kindly check the GIF below:

![missingannotation_gif(1)](https://user-images.githubusercontent.com/17806022/115664490-5480a300-a35b-11eb-9f07-370005d1c130.gif)

@kmehmoodkhan FYI

**Comment by bobkovalex** [comment]
@ImSMRizwan 

Please check annotated document locally using Adobe Reader instead of Chrome built-in PDF viewer.

Regards,
Alex

**Comment by ImSMRizwan** [comment]
@bobkovalex Thanks for your comment. let me check.

**Comment by ImSMRizwan** [comment]
@bobkovalex Thanks for your support, above mentioned issues are fixed and working fine, But Now I am facing another issue, I want to share the issue, Kindly check the GIF file below.

![adjustmentissuegif](https://user-images.githubusercontent.com/17806022/115921597-2606e300-a495-11eb-838d-6b2569ddc1c8.gif)

Actually, When I saved the image file the annotation position is changed.

**Comment by ImSMRizwan** [comment]
@bobkovalex  @kegor, any updates

**Comment by ImSMRizwan** [comment]
@bobkovalex and @kegor, I have found another glitch kindly check the GIF file below and also png file attached. kindly find the attachment.

![22](https://user-images.githubusercontent.com/17806022/116190150-89b63800-a743-11eb-9e0c-23d1abc7409a.PNG)

![Uploading formateerror_gif.gif…]()

**Comment by ImSMRizwan** [comment]
@bobkovalex, Kindly update me above issue, which was shared 3 days ago, The issue is some annotations position are not correct after saved.

> @bobkovalex Thanks for your support, above mentioned issues are fixed and working fine, But Now I am facing another issue, I want to share the issue, Kindly check the GIF file below.
> 
> ![adjustmentissuegif](https://user-images.githubusercontent.com/17806022/115921597-2606e300-a495-11eb-838d-6b2569ddc1c8.gif)
> 
> Actually, When I saved the image file the annotation position is changed. Kindly check all annotations position on image/pdf also.
> 
> @kmehmoodkhan FYI
> 
> Thanks, best regards

@bobkovalex Any update?

**Comment by kegor** [comment]
Hi @ImSMRizwan,

The issue on save action mentioned in following [comment](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/issues/67#issuecomment-827323541) has been resolved. Please checkout latest commit from master branch GroupDocs.Annotation-for-.NET-MVC.

The issue with positions of annotations added on image-files mentioned in following [comment](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/issues/67#issuecomment-825877794) is under investigation.

Thank you,
Egor.

**Comment by ImSMRizwan** [comment]
> Hi @ImSMRizwan,
> 
> The issue on save action mentioned in following [comment](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/issues/67#issuecomment-827323541) has been resolved. Please checkout latest commit from master branch GroupDocs.Annotation-for-.NET-MVC.
> 
> The issue with positions of annotations added on image-files mentioned in following [comment](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/issues/67#issuecomment-825877794) is under investigation.
> 
> Thank you,
> Egor.

Ok sure, kindly check also pdf file, and also check The point annotation on a pdf file,

**Comment by ImSMRizwan** [comment]
@bobkovalex and @kegor, any update?

**Comment by kegor** [comment]
Hi @ImSMRizwan,

The issue with positions of annotations added on image-files mentioned in following [comment](https://github.com/groupdocs-annotation/GroupDocs.Annotation-for-.NET-MVC/issues/67#issuecomment-825877794) has been partially resolved.  Please checkout latest commit from master branch GroupDocs.Annotation-for-.NET-MVC.

However, there are still two issues with annotations length and text underline annotation position. We expect that they will be fixed in the next library version. 

Thank you,
Egor.
